export const ActionTypes = {
  FETCH_CURREENT_WEATHER_DETAILS_REQUEST:
    'FETCH_CURREENT_WEATHER_DETAILS_REQUEST',
  FETCH_CURRENT_WEATHER_DETAILS: 'FETCH_CURRENT_WEATHER_DETAILS',
  FETCH_CURRENT_WEATHER_DETAILS_FAILURE:
    'FETCH_CURRENT_WEATHER_DETAILS_FAILURE',
  CHANGE_FAVOURITE_STATE: 'CHANGE_FAVOURITE_STATE',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
}
